services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    port:
      - 5432:5432
    enviroment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=database_ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mod: host
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mod: host

volumes:
  pgdata: 
    driver: local
