version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    container_name: database_ignite
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rentx
    volumes: 
      - pgdata:/data/postgres
    networks:
      - host
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - host
    depends_on:
      - db

volumes:
  pgdata:
    driver: local

networks:
  host:
    driver: bridge